RESTORE DATABASE AFVServer
FROM DISK = 'c:\BKAFV\BKAFV.bak'
WITH FILE = 1, 
MOVE 'AFVServer_PADRAO_Data' TO 'c:\DB\AFVServerSOBEL.mdf',
MOVE 'AFVServer_PADRAO_log' TO 'c:\DB\AFVServerSOBEL.ldf'
GO



RESTORE FILELISTONLY
FROM DISK = 'c:\BKAFV\BKAFV.bak'
