
SELECT D_E_L_E_T_, C9_BLEST, * FROM SC9040
WHERE C9_ROMANEI = '001882'
AND C9_PEDIDO IN ('093188', '0')
GO

/**
 STATUS - L (LIBERADO ADM-VENDAS)
          D (LIBERADO PARA ROMANEIO)
          T (EM ROMANEIO)
 **/