USE Protheus_Producao
GO
SELECT EMPRESA = 'SOBEL',
       SC5.C5_NUM,
       SF2.F2_DOC,
	   SC5.C5_NOTA,
       SC5.C5_ROMANEI,
	   SC5.C5_QTDPED,
	   C6_QTDVEN = (SELECT SUM(SC6.C6_QTDVEN) AS C6_QTDEVEN
					FROM SC6010 SC6 
					WHERE SC6.C6_NUM = SC5.C5_NUM 
					AND   SC6.D_E_L_E_T_ = ''
		),
		C9_QTDLIB =(SELECT SUM(SC9.C9_QTDLIB) AS C9_QTDLIB
					FROM SC9010 SC9 
					WHERE SC9.C9_PEDIDO = SC5.C5_NUM
					AND   SC9.D_E_L_E_T_ = ''
		),
	    D2_QUANT = (SELECT SUM(SD2.D2_QUANT) AS D2_QUANT
					FROM SD2010 SD2 
					WHERE SD2.D2_PEDIDO = SC5.C5_NUM
					AND   SD2.D_E_L_E_T_ = ''
		), 
		SC5.C5_EMISSAO,       
		SF2.F2_EMISSAO,
		DATEDIFF(DAY,SC5.C5_EMISSAO, SF2.F2_EMISSAO) AS DIAS,
		SF2.F2_HORA,
		SF2.F2_CHVNFE,		
		'NF_CHV' = SUBSTRING(SF2.F2_CHVNFE,26,9)		
FROM SC5010 SC5
LEFT JOIN SF2010 SF2 ON SF2.F2_DOC = SC5.C5_NOTA
WHERE SC5.D_E_L_E_T_ = ''
  AND SF2.D_E_L_E_T_ = ''
  AND SC5.C5_STAPED = 'F'
  AND SC5.C5_ZZTIPO <> 'L'
--AND CAST(SC5.C5_EMISSAO AS DATE) BETWEEN '20180601' AND GETDATE() 
  AND CAST(SC5.C5_EMISSAO AS DATE) >= GETDATE() - 120  
ORDER BY SC5.C5_EMISSAO DESC