USE Protheus_Producao
GO
DECLARE @DTINI AS DATE,
        @DTFIN AS DATE

SET @DTINI =  GETDATE() - 90
SET @DTFIN =  GETDATE()

SELECT EMPRESA = 'SOBEL',
       SC5.C5_NUM,
	   SA1.A1_COD, 
	   SA1.A1_NOME,
       SF2.F2_DOC,
	   SC5.C5_NOTA,
       SC5.C5_ROMANEI,
	   SC5.C5_QTDPED,
	   C6_QTDVEN = (SELECT SUM(SC6.C6_QTDVEN) 
					FROM SC6010 SC6 
					WHERE SC6.C6_NUM = SC5.C5_NUM 
					AND   SC6.D_E_L_E_T_ = ''
		),
		C9_QTDLIB =(SELECT SUM(SC9.C9_QTDLIB)
					FROM SC9010 SC9 
					WHERE SC9.C9_PEDIDO = SC5.C5_NUM
					AND   SC9.D_E_L_E_T_ = ''
		),
	    D2_QUANT = (SELECT SUM(SD2.D2_QUANT)
					FROM SD2010 SD2 
					WHERE SD2.D2_PEDIDO = SC5.C5_NUM
					AND   SD2.D_E_L_E_T_ = ''
		), 
		SC5.C5_EMISSAO,       
		SF2.F2_EMISSAO,
		--CONVERT(VARCHAR(10),CAST(SF2.F2_EMISSAO AS DATE), 103) AS F2_EMISSAO,
		DATEDIFF(DAY,SC5.C5_EMISSAO, SF2.F2_EMISSAO) AS DIAS,
		SF2.F2_HORA,
		SF2.F2_CHVNFE,		
		'NF_CHV' = SUBSTRING(SF2.F2_CHVNFE,26,9)		
FROM SC5010 SC5
LEFT JOIN SF2010 SF2 ON SF2.F2_DOC = SC5.C5_NOTA
INNER JOIN SA1010 SA1 ON SA1.A1_COD = SF2.F2_CLIENTE
WHERE SC5.D_E_L_E_T_ = ''
  AND SF2.D_E_L_E_T_ = ''
  AND SF2.F2_CHVNFE <> ''
  AND SC5.C5_STAPED = 'F'
  AND SC5.C5_ZZTIPO <> 'L'
  AND CAST(SC5.C5_EMISSAO AS DATE) BETWEEN @DTINI AND @DTFIN
--AND CAST(SC5.C5_EMISSAO AS DATE) >= GETDATE() - 120  

UNION ALL

SELECT EMPRESA = 'JMT',
       SC5.C5_NUM,
	   SA1.A1_COD, 
	   SA1.A1_NOME,
       SF2.F2_DOC,
	   SC5.C5_NOTA,
       SC5.C5_ROMANEI,
	   SC5.C5_QTDPED,
	   C6_QTDVEN = (SELECT SUM(SC6.C6_QTDVEN)
					FROM SC6020 SC6 
					WHERE SC6.C6_NUM = SC5.C5_NUM 
					AND   SC6.D_E_L_E_T_ = ''
		),
		C9_QTDLIB =(SELECT SUM(SC9.C9_QTDLIB)
					FROM SC9020 SC9 
					WHERE SC9.C9_PEDIDO = SC5.C5_NUM
					AND   SC9.D_E_L_E_T_ = ''
		),
	    D2_QUANT = (SELECT SUM(SD2.D2_QUANT)
					FROM SD2020 SD2 
					WHERE SD2.D2_PEDIDO = SC5.C5_NUM
					AND   SD2.D_E_L_E_T_ = ''
		), 
		SC5.C5_EMISSAO,       
		SF2.F2_EMISSAO,
		DATEDIFF(DAY,SC5.C5_EMISSAO, SF2.F2_EMISSAO) AS DIAS,
		SF2.F2_HORA,
		SF2.F2_CHVNFE,		
		'NF_CHV' = SUBSTRING(SF2.F2_CHVNFE,26,9)		
FROM SC5020 SC5
LEFT JOIN SF2020 SF2 ON SF2.F2_DOC = SC5.C5_NOTA
INNER JOIN SA1020 SA1 ON SA1.A1_COD = SF2.F2_CLIENTE
WHERE SC5.D_E_L_E_T_ = ''
  AND SF2.D_E_L_E_T_ = ''
  AND SF2.F2_CHVNFE <> ''
  AND SC5.C5_STAPED = 'F'
  AND SC5.C5_ZZTIPO <> 'L'
  AND CAST(SC5.C5_EMISSAO AS DATE) BETWEEN @DTINI AND @DTFIN
--AND CAST(SC5.C5_EMISSAO AS DATE) >= GETDATE() - 120

UNION ALL

SELECT EMPRESA = '3F',
       SC5.C5_NUM,
	   SA1.A1_COD, 
	   SA1.A1_NOME,
       SF2.F2_DOC,
	   SC5.C5_NOTA,
       SC5.C5_ROMANEI,
	   SC5.C5_QTDPED,
	   C6_QTDVEN = (SELECT SUM(SC6.C6_QTDVEN)
					FROM SC6040 SC6 
					WHERE SC6.C6_NUM = SC5.C5_NUM 
					AND   SC6.D_E_L_E_T_ = ''
		),
		C9_QTDLIB =(SELECT SUM(SC9.C9_QTDLIB)
					FROM SC9040 SC9 
					WHERE SC9.C9_PEDIDO = SC5.C5_NUM
					AND   SC9.D_E_L_E_T_ = ''
		),
	    D2_QUANT = (SELECT SUM(SD2.D2_QUANT)
					FROM SD2040 SD2 
					WHERE SD2.D2_PEDIDO = SC5.C5_NUM
					AND   SD2.D_E_L_E_T_ = ''
		), 
		SC5.C5_EMISSAO,       
		SF2.F2_EMISSAO,
		DATEDIFF(DAY,SC5.C5_EMISSAO, SF2.F2_EMISSAO) AS DIAS,
		SF2.F2_HORA,
		SF2.F2_CHVNFE,		
		'NF_CHV' = SUBSTRING(SF2.F2_CHVNFE,26,9)		
FROM SC5040 SC5
LEFT JOIN SF2040 SF2 ON SF2.F2_DOC = SC5.C5_NOTA
INNER JOIN SA1040 SA1 ON SA1.A1_COD = SF2.F2_CLIENTE
WHERE SC5.D_E_L_E_T_ = ''
  AND SF2.D_E_L_E_T_ = ''
  AND SF2.F2_CHVNFE <> ''
  AND SC5.C5_STAPED = 'F'
  AND SC5.C5_ZZTIPO <> 'L'
  AND CAST(SC5.C5_EMISSAO AS DATE) BETWEEN @DTINI AND @DTFIN 
--AND CAST(SC5.C5_EMISSAO AS DATE) >= GETDATE() - 120
ORDER BY SC5.C5_EMISSAO DESC
GO

