CREATE TRIGGER TGR_SETOR_UPDATE ON tst_controle_acesso.dbo.PESSOA
AFTER INSERT
AS
BEGIN
      DECLARE @RECNO INT
	  SET @RECNO = (SELECT IDENT_CURRENT ('PESSOA'))
	  UPDATE PESSOA 
	  SET SETOR = 'N/D'
	  WHERE ID = @RECNO;
END
GO

--TESTE
--INSERT INTO PESSOA (NOME) VALUES ('TESTE')

