SELECT *
FROM AFVServer_SOBEL_PRD.dbo.T$_USUARIO
WHERE SENHA = '<CRIP>÷õº¼¶³µ¶'
GO

SELECT *
FROM AFVServer_SOBEL_PRD.dbo.T$_USUARIO
WHERE USUARIO = 'rp336.01'
GO

--SELECT *
--FROM Protheus_Teste12.dbo.SA1020 
--WHERE A1_CGC = '11161187000121'
--GO


SELECT *
FROM T_CLIENTENOVO_SOBEL
GO

SELECT *
FROM Protheus_Teste12.dbo.T_CLIENTENOVO_SOBEL
GO

/*
FLAGUSO = 1 (ativo - aparece no tablet e na web)
FLAGUSO = 0 (inativo - não aparece no tablet e na web)CODIGOSTATUSPROD = SEMPRE APARECE.. de acordo com as regras do ERP.. atualmente no caso de vcs:
Se for 1 = Bloqueado para Venda
Se for 2 = Liberado para Venda
*/

--UPDATE Protheus_Teste12.dbo.T_CLIENTENOVO_SOBEL
--SET D_E_L_E_T_ = '*'
--WHERE SEQUENCIA IN (34, 35, 36) 


------------------------------------------------------------------
--Tabela Cabeçalho Pedido de Venda
------------------------------------------------------------------
USE Protheus_Producao
GO
SELECT CODIGOUNIDFAT, * 
FROM T_PEDIDO_SOBEL
WHERE NUMPEDIDOSOBEL = '098483'
ORDER BY NUMPEDIDO DESC
GO

SELECT DATALIBERACAO, FLAGBLOQUEIOAFV, * 
FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO
ORDER BY NUMPEDIDO DESC
GO

/*
SELECT NUMPEDIDO,
	   A3_NOME AS NOMEVEND, 
	   CODIGOUNIDFAT
FROM T_PEDIDO_SOBEL
INNER JOIN SA3020 SA3 ON SA3.A3_COD = CODIGOVENDEDORESP
WHERE NUMPEDIDO >= 591
ORDER BY CODIGOUNIDFAT
GO
*/


SELECT *
FROM T_PEDIDO_SOBEL 
WHERE NUMPEDIDOAFV = '1554648556178'
GO




SELECT * FROM T_PEDIDOITEM_SOBEL
WHERE NUMPEDIDO = '444'


SELECT *
FROM AFVServer_SOBEL.dbo.T_VENDEDOR
WHERE CODIGOVENDEDORESP = '000573.01'
GO


-------------------------------------------------------------------
/* ANALISE AMARRAÇÃO BONIFICAÇÃO */

USE Protheus_Teste12
GO
SELECT CODIGOUNIDFAT, * 
FROM T_PEDIDO_SOBEL
WHERE NUMPEDIDOAFV = 'W1550703190855321'
ORDER BY NUMPEDIDO DESC
GO

------------------------------------------------------------------
--Tabela detalhe Pedido de Venda
------------------------------------------------------------------
SELECT * 
FROM T_PEDIDOITEM_SOBEL
WHERE NUMPEDIDOAFV = '1550170526792'
GO
------------------------------------------------------------------
/* CONSULTA PEDIDOS NO AFV */
SELECT DATALIBERACAO, FLAGBLOQUEIOAFV, * 
FROM AFVServer_SOBEL.dbo.T_PEDIDO
ORDER BY NUMPEDIDO DESC
GO

-----------------------------------------------------------------------------------------------

USE Protheus_Teste12
GO
SELECT CODIGOUNIDFAT, * 
FROM T_PEDIDO_SOBEL
WHERE NUMPEDIDOAFV = '1550854814440'
ORDER BY NUMPEDIDO DESC
GO

USE Protheus_Teste12
GO
SELECT CODIGOUNIDFAT, * 
FROM T_PEDIDO_SOBEL
WHERE NUMPEDIDOSOBEL = '097471'
ORDER BY NUMPEDIDO DESC
GO


SELECT FLAGBLOQUEIOAFV,* 
FROM AFVServer_SOBEL.dbo.T_PEDIDO
WHERE NUMPEDIDOAFV = '1550854814440'
ORDER BY NUMPEDIDO DESC
GO

SELECT * 
FROM AFVServer_SOBEL.dbo.T_PEDIDO
WHERE FLAGBLOQUEIOAFV = 'S'
ORDER BY NUMPEDIDO DESC
GO


SELECT C5_ZZPEDCL, *
FROM SC5040
WHERE C5_NUM = '097491'
GO

sp_help 'SC5040'

/* CONTROLE APROVADOR ACACIA */
SELECT * 
FROM AFVServer_SOBEL.dbo.T$_CONTROLEAPROVADOR
WHERE NUMPEDIDO = '437'



/* CONTROLE APROVADOR ACACIA */
SELECT * 
FROM AFVServer_SOBEL.dbo.T$_CONTROLEAPROVADOR
WHERE STATUS = 'P'



/* Forçar workflow a enviar email novamente. */
UPDATE AFVServer_SOBEL_PRD.dbo.T$_CONTROLEAPROVADOR 
SET INICIONOTIFICACAO = NULL,
	ULTIMANOTIFICACAO = NULL
WHERE NUMPEDIDO = 1001
GO


----------------------------------------------------
/* RETORNA TODOS OS PEDIDOS PENDENTES DE APROVAÇÃO */
SELECT * 
FROM AFVServer_SOBEL.dbo.T$_CONTROLEAPROVADOR
WHERE NUMPEDIDO IN ( SELECT NUMPEDIDO 
					FROM AFVServer_SOBEL.dbo.T_PEDIDO
					WHERE FLAGBLOQUEIOAFV = 'S')


/*Consulta ultimas vendas do representante no protheus*/
USE Protheus_Producao
SELECT *
FROM SF2010 
WHERE F2_VEND1 = '000573'
GO

/* USUÁRIOS AFVSERVERWEB */
SELECT * 
FROM AFVServer_SOBEL.dbo.T$_USUARIO 
WHERE CODIGO = 7


USE AFVServer_SOBEL
GO
EXEC P_EXECUTARSCRIPTIMPORT TE_TABELAPRECO
GO

SELECT *
FROM TE_TABELAPRECO
WHERE CODIGOPRODUTO = 'VERBA          .04'


USE AFVServer_SOBEL
GO
EXEC P_EXECUTARSCRIPTIMPORT TE_TABELAPRECO
GO
/* TE = ERP | TR = RELACIONAMENTO | T_ = AFV | TC = ESTRUTURA | T$ = CONFIG. | TWF = WORKFLOW | V_ VIEW PROTHEUS */


SELECT * FROM TE_TABELAPRECO
WHERE CODIGOPRODUTO LIKE 'VERBA%'
----------------------------------------------------------------------------------------------------------------

/* SCRIPTS DE VALIDAÇÃO CLIENTE BLOQUEADO OU INESISTENTE NO AFV */

--SELECT A1_MSBLQL, A1_VEND, *
--FROM Protheus_Teste12.dbo.SA1020 
--WHERE A1_CGC = '09266567000189'
--GO

/* QUERY TESTE SA1 */
--UPDATE Protheus_Teste12.dbo.SA1020 
--SET A1_MSBLQL = '1'
--WHERE A1_CGC = '09266567000189'
--GO

USE AFVServer_SOBEL
GO

SELECT CODIGOSTATUSCLI, * FROM TE_CLIENTE
WHERE CGCCPF = '49092398000394'
GO

SELECT * FROM TR_CLIENTEVENDEDOR
WHERE CODIGOCLIENTE = '013906.01.04'
GO
