DECLARE @NUMPEDIDOAFVBONI VARCHAR(MAX)
	SET @NUMPEDIDOAFVBONI = 'W1150904191140599'

SELECT * 
FROM(
      SELECT   NUMPEDIDOSOBEL,
				CODIGOCLIENTE,
				NUMPEDIDOAFV,
				CODIGOTIPOPEDIDO 
		 FROM Protheus_Producao.dbo.T_PEDIDO_SOBEL B 
		 WHERE B.NUMPEDIDOAFV COLLATE Latin1_General_CI_AS IN 
		  (
			SELECT TAB.ITENS 
			FROM Protheus_Producao.dbo.T_PEDIDO_SOBEL PED 
			CROSS APPLY Protheus_Producao.dbo.F_SPLIT(ISNULL(PED.CESP_NUMPEDIDOASSOC,''),';') TAB 
			WHERE PED.NUMPEDIDOAFV = @NUMPEDIDOAFVBONI
		  )
	  ) C 
WHERE C.CODIGOCLIENTE =  (
						  SELECT CODIGOCLIENTE 
						  FROM Protheus_Producao.dbo.T_PEDIDO_SOBEL 
						  WHERE NUMPEDIDOAFV = @NUMPEDIDOAFVBONI
						  ) 
GO


--'002982'

--SELECT TAB.ITENS 
--FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO PED 
--     CROSS APPLY AFVServer_SOBEL_PRD.dbo.F_SPLIT(ISNULL(PED.CESP_NUMPEDIDOASSOC,''),';') TAB
--WHERE PED.NUMPEDIDOAFV = ''