USE Protheus_Producao
GO
/* Retorna pedidos na tabela intermediária */
SELECT CODIGOUNIDFAT, * 
FROM T_PEDIDO_SOBEL
--WHERE CODIGOCLIENTE ='015762.15.04'
--WHERE NUMPEDIDOSOBEL = '098650'
--WHERE NUMPEDIDOAFV = 'W911004190939469'
--WHERE CODIGOVENDEDORESP = '000212'
--WHERE CODIGOTIPOPEDIDO = 'F'
ORDER BY NUMPEDIDO DESC
GO


SELECT *
FROM T_PEDIDOITEM_SOBEL
WHERE NUMPEDIDOAFV = '1554649727251'


/*PV BLQ WITH VEND */
SELECT FLAGBLOQUEIOAFV, *
FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO 
WHERE CODIGOVENDEDORESP = '000091.04'
AND FLAGBLOQUEIOAFV = 'S'
GO


SELECT  FLAGBLOQUEIOAFV, *
FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO 
WHERE CODIGOVENDEDORESP = '000212.04'
ORDER BY NUMPEDIDO DESC
GO


--W50204190750588
/*Tabela de Pedidos AFV Acacia */
SELECT *
FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO
--WHERE NUMPEDIDOAFV = 'W910204191451271'
ORDER BY NUMPEDIDO DESC
GO


SELECT *
FROM AFVServer_SOBEL_PRD.dbo.T$_USUARIO
WHERE USUARIO = 'rp533.01'
GO

SELECT * FROM AFVServer_SOBEL_PRD.dbo.T$_USUARIO
WHERE CODIGO = 5 

/* Consulta de Vendedores */
SELECT *
FROM AFVServer_SOBEL_PRD.dbo.T_VENDEDOR


/* Retorna pedidos bloqueados */
SELECT USUARIORESP,
       US.NOME,
	   US.EMAIL,
       * 		
FROM AFVServer_SOBEL_PRD.dbo.T$_CONTROLEAPROVADOR AP
INNER JOIN AFVServer_SOBEL_PRD.dbo.T$_USUARIO US ON US.CODIGO = AP.USUARIORESP
WHERE NUMPEDIDO IN 
(
	SELECT NUMPEDIDO
	FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO
	WHERE FLAGBLOQUEIOAFV = 'S'
	--AND NUMPEDIDO IN (1168, 1169,1170)
)
GO


SELECT * 
FROM AFVServer_SOBEL_PRD.dbo.T$_CONTROLEAPROVADOR 
WHERE NUMPEDIDO = 1012


--SELECT C5_EMISSAO, *
--FROM Protheus_Producao.dbo.SC5040 
--WHERE C5_NUM IN ('','098483', '098486')
--GO


SELECT * 
FROM SA1020
WHERE A1_VEND = '000569'
AND D_E_L_E_T_ = ''


SELECT *
FROM AFVServer_SOBEL_PRD.dbo.T$_USUARIO
GO

SELECT *
FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO
WHERE NUMPEDIDOAFV = 'W1520104191522575'
GO



SELECT * 
FROM AFVServer_SOBEL_PRD.dbo.T$_CONTROLEAPROVADOR
WHERE NUMPEDIDO = 799




SELECT * FROM AFVServer_SOBEL_PRD.dbo.T$_USUARIO
WHERE USUARIO = 'rp533.01'
GO

--rp533.01


