BEGIN TRANSACTION 
UPDATE AFVServer_SOBEL.dbo.TE_HISTPEDIDO 
SET STATUSPEDIDO = 'ROMANEIO'
WHERE STATUSPEDIDO = 'T'
GO
SELECT * 
FROM AFVServer_SOBEL.dbo.TE_HISTPEDIDO
WHERE STATUSPEDIDO IN ('S','M','C','R','A','L','D','T','O','P','F')
GO

COMMIT



    