BEGIN TRANSACTION
UPDATE AFVServer_SOBEL_PRD.dbo.T$_LAYOUTEMAIL 
SET SQLITENS = 'SELECT    PDI.NUMPEDIDO,    
          PDI.NUMITEM,   
		  PDI.CODIGOPRODUTO,   
		  PR.DESCRICAO ,   
		  PDI.QTDEVENDA,   ''R$ '' + CAST(REPLACE(CONVERT(VARCHAR,CAST(ROUND( COALESCE(PDI.VALORBRUTO, 0.0000) , 2) AS MONEY), 1), '','',''.'') AS VARCHAR(30)) AS VALORBRUTO,    
		  --COALESCE(PDI.DESCONTOI, 0) AS DESCI,   
		  CAST(COALESCE(PDI.DESCONTOI, 0) AS DECIMAL(10,2)) AS DESCI,   
		  COALESCE(PDI.DESCONTOII, 0) AS DESCII,   
		  COALESCE(PDI.DESCONTOIII, 0) AS DESCIII,   
		  ''R$ '' + CAST(REPLACE(CONVERT(VARCHAR,CAST(ROUND( COALESCE(PDI.VALORVENDA, 0.0000) , 2) AS MONEY), 1), '','',''.'') AS VARCHAR(30)) AS VALORLIQUIDO   
		  FROM T_PEDIDOITEM PDI   INNER JOIN TE_PRODUTO PR ON (PR.CODIGO = PDI.CODIGOPRODUTO)  
		  WHERE NUMPEDIDO = {PEDIDO}'
WHERE CODIGO = 1
GO
SELECT * FROM AFVServer_SOBEL_PRD.dbo.T$_LAYOUTEMAIL
GO
--COMMIT

PRINT 
'SELECT    PDI.NUMPEDIDO,    
          PDI.NUMITEM,   
		  PDI.CODIGOPRODUTO,   
		  PR.DESCRICAO ,   
		  PDI.QTDEVENDA,   ''R$ '' + CAST(REPLACE(CONVERT(VARCHAR,CAST(ROUND( COALESCE(PDI.VALORBRUTO, 0.0000) , 2) AS MONEY), 1), '','',''.'') AS VARCHAR(30)) AS VALORBRUTO,    
		  --COALESCE(PDI.DESCONTOI, 0) AS DESCI,   
		  CAST(COALESCE(PDI.DESCONTOI, 0) AS DECIMAL(10,2)) AS DESCI,   
		  COALESCE(PDI.DESCONTOII, 0) AS DESCII,   
		  COALESCE(PDI.DESCONTOIII, 0) AS DESCIII,   
		  ''R$ '' + CAST(REPLACE(CONVERT(VARCHAR,CAST(ROUND( COALESCE(PDI.VALORVENDA, 0.0000) , 2) AS MONEY), 1), '','',''.'') AS VARCHAR(30)) AS VALORLIQUIDO   
		  FROM T_PEDIDOITEM PDI   INNER JOIN TE_PRODUTO PR ON (PR.CODIGO = PDI.CODIGOPRODUTO)  
		  WHERE NUMPEDIDO = {PEDIDO}'


