SELECT *
FROM AFVServer_SOBEL.dbo.T_MUNICIPIO
GO

SELECT * 
FROM AFVServer_SOBEL.dbo.V_MUNICIPIOIBGE
WHERE RIGHT(CODIGONOMECIDADE, 2)  = 'RS'
GO

--BEGIN TRANSACTION
--UPDATE SA1010 SET A1_MUN = 'SAO PAULO'
--WHERE R_E_C_N_O_= 1402
--GO
--SELECT R_E_C_N_O_,*
--FROM SA1010 
--WHERE R_E_C_N_O_ = 1402
--GO
--ROLLBACK