SET DATEFORMAT ymd; 
SELECT A.ACESSO AS H_ACESSO, 
       P.ID AS T_CODIGO,	   
       A.TIPO_ACESSO AS T_ACESSO, 
       P.NOME AS T_NOME,
       P.SETOR,CONVERT(VARCHAR(5),A.ACESSO,108) AS HORA_ACESSO 
FROM ACESSO A 
INNER JOIN PESSOA P 
ON P.ID = A.ID_PESSOA 
WHERE P.SETOR = 'LABORATÓRIO' AND A.ACESSO BETWEEN '2018-10-17' AND '2018-10-18' 
GROUP BY  P.ID, 
          P.NOME, 
		  P.SETOR, 
		  A.ACESSO, 
		  A.TIPO_ACESSO 
ORDER BY T_NOME ASC