/* SD1 NOTAS FISCAIS */
SELECT D1_COD, 
       SUM(D1_CUSTO) AS CUSTO,
	   SUM(D1_CUSTO2) AS CUSTO2,
	   SUM(D1_CUSTO3) AS CUSTO3,
	   SUM(D1_CUSTO4) AS CUSTO4,
	   SUM(D1_CUSTO5) AS CUSTO5
FROM SD1040 
WHERE D1_EMISSAO >= GETDATE() - 90
AND D1_CUSTO < 0
GROUP BY D1_COD
GO

/* SD2 ITENS DE VENDA NF */
SELECT D2_COD, 
       SUM(D2_CUSTO1) AS CUSTO1,
	   SUM(D2_CUSTO2) AS CUSTO2,
	   SUM(D2_CUSTO3) AS CUSTO3,
	   SUM(D2_CUSTO4) AS CUSTO4,
	   SUM(D2_CUSTO5) AS CUSTO5
FROM SD2040 
WHERE D2_EMISSAO >= GETDATE() - 90
AND D2_CUSTO1 < 0
GROUP BY D2_COD
GO

/* SD3 MOVIMENTAÇÕES INTERNAS */
SELECT D3_COD, 
       SUM(D3_CUSTO1) AS CUSTO1,
	   SUM(D3_CUSTO2) AS CUSTO2,
	   SUM(D3_CUSTO3) AS CUSTO3,
	   SUM(D3_CUSTO4) AS CUSTO4,
	   SUM(D3_CUSTO5) AS CUSTO5
FROM SD3040 
WHERE D3_EMISSAO >= GETDATE() - 90
AND D3_CUSTO1 < 0
GROUP BY D3_COD
GO

/*SB2 ESTOQUE DE PRODUTOS */
SELECT B2_COD,
       SUM(B2_VFIM1) AS VFIM1,
	   SUM(B2_VFIM2) AS VFIM2,
	   SUM(B2_VFIM3) AS VFIM3,
	   SUM(B2_VFIM4) AS VFIM4,
	   SUM(B2_VFIM5) AS VFIM5
FROM SB2040 
WHERE B2_VFIM1 < 0 
GROUP BY B2_COD
GO

