
SET DATEFORMAT ymd;
SELECT ACESSO.ACESSO AS H_ACESSO,
PESSOA.ID as T_CODIGO,
ACESSO.TIPO_ACESSO as T_ACESSO,
PESSOA.NOME as T_NOME,
CONVERT(VARCHAR(5),ACESSO.ACESSO,108) AS HORA_ACESSO 
from acesso
INNER JOIN PESSOA on PESSOA.ID = ACESSO.ID_PESSOA
WHERE PESSOA.ID IN (SELECT ID_PESSOA FROM PESSOA)
AND ACESSO.ACESSO BETWEEN '2018-09-01' AND '2018-09-06'
ORDER BY T_NOME ASC 





