DECLARE
        @STARTDATE DATE,
        @ENDDATE DATE

SET @STARTDATE = '20150701';
SET @ENDDATE = '20150705';

WITH DATERANGE AS
(
  SELECT DT = @STARTDATE
  WHERE @STARTDATE < @ENDDATE
  UNION ALL
  		SELECT DATEADD(DAY, 1, DT)
  		FROM DATERANGE
  		WHERE DATEADD(DAY, 1, DT) <= @ENDDATE
)
SELECT CONVERT(VARCHAR(MAX),DT,103)
FROM DATERANGE
GO