USE Protheus_Producao
GO

DECLARE @TABLECLIJMT TABLE (ID INT IDENTITY, CODCLI VARCHAR(10))
DECLARE @TABLECLI3F TABLE (ID INT IDENTITY, CODCLI VARCHAR(10), NOMECLI VARCHAR(100))
DECLARE @STATUS      AS VARCHAR(10),
		@CONT        AS INT,
		@NCLIBLQ     AS INT,
		@CODCLI3F    AS VARCHAR(10),
		@NOMECLI3F   AS VARCHAR(100)

SET @CONT       = 1
SET @CODCLI3F   = ''
SET @NOMECLI3F  = ''
SET @NCLIBLQ = (SELECT COUNT(A1_COD) FROM SA1020 WHERE A1_MSBLQL <> 1 AND D_E_L_E_T_ = '')

	--ADD DADOS DE CLIENTES BLOQUEADOS NA TEMP TABLE
	INSERT INTO @TABLECLIJMT (CODCLI) 
	SELECT A1_COD FROM SA1020 WHERE A1_MSBLQL <> 1 AND D_E_L_E_T_ = ''	

BEGIN	
	WHILE @CONT <= @NCLIBLQ
	BEGIN
		SET @CODCLI3F  = (SELECT A1_COD FROM SA1040 WHERE A1_COD = (SELECT CODCLI FROM @TABLECLIJMT WHERE ID = @CONT) AND A1_MSBLQL  <> 2 AND D_E_L_E_T_ = '')
		SET @NOMECLI3F = (SELECT A1_NOME FROM SA1040 WHERE A1_COD = (SELECT CODCLI FROM @TABLECLIJMT WHERE ID = @CONT) AND A1_MSBLQL <> 2 AND D_E_L_E_T_ = '')

		IF @CODCLI3F <> ''
			BEGIN 
				INSERT INTO @TABLECLI3F (CODCLI, NOMECLI) VALUES (@CODCLI3F, @NOMECLI3F)
			END

		/* CRIAR UPDATE AQUI CASO SEJA NECESSÁRIO */
				


		SET @CONT += 1
	END
	/*TESTE DE SAÍDA*/
	SELECT * FROM @TABLECLI3F

	

END		


