/*-CONSULTAR CODIGO E DESCRICAO DO CADASTRO DE PRODUTO*/ 

SELECT B1_COD,
       B1_DESC 
FROM SB1010 

/*-CONSULTAR NOME E EMAIL NO CADASTRO SA1 (CLIENTES)*/ 

SELECT A1_NOME,
       A1_EMAIL 
FROM SA1010 

/*-CONSULTAR O CODIGO E A DESCRIÇÃO DO PRODUTO CONTENDO A PALAVRA "AGUA" */ 
SELECT C7_PRODUTO, 
       C7_DESCRI 
FROM SC7010 
WHERE C7_DESCRI LIKE (‘AGUA%‘)     

/*-CONSULTAR O NUMERO DO PEDIDO COM A DESCRIÇÃO CONTENDO A PALAVRA FERRO*/ 
SELECT C7_NUM, 
       C7_DESCRI 
 FROM SC7010 
 WHERE C7_DESCRI LIKE ‘FERRO% 