SELECT C5_CLIENT, 
       C5_CLIENTE, 
       C5_COMIS1, 
       C5_COMIS2, 
       C5_COMIS3, 
       C5_CONDPAG, 
       C5_EMISSAO, 
       C5_FILIAL, 
       C5_LIBEROK, 
       C5_LOJACLI, 
       C5_LOJAENT, 
       C5_MENNOTA, 
       C5_NOTA, 
       C5_NUM, 
       C5_SERIE, 
       C5_TABELA, 
       C5_TIPLIB, 
       C5_TIPO, 
       C5_TIPOCLI, 
       C5_TRANSP, 
       C5_VEND1, 
       C5_VEND2, 
       C5_VEND3, 
       C5_ZZOBS1, 
       C5_ZZTIPO, 
       SC5.R_E_C_N_O_ AS RECNUM, 
       SC5.D_E_L_E_T_ AS DELET 
FROM SC5010 SC5 
WHERE (SC5.D_E_L_E_T_ = @0 OR SC5.D_E_L_E_T_ IS NULL) AND C5_EMISSAO >= @1 
ORDER BY SC5.R_E_C_N_O_ DESC