USE controle_acesso
GO
SET DATEFORMAT ymd; 
SELECT P.NOME,
       A.ACESSO, 
	   "TIPO_ACESSO" = 
	   CASE A.TIPO_ACESSO
		 WHEN 'E' THEN 'ENTRADA' 
		 WHEN 'S' THEN 'SAÍDA' 
       END    
FROM ACESSO A
INNER JOIN PESSOA P ON A.ID_PESSOA = P.ID
WHERE ID_PESSOA = 27
AND ACESSO BETWEEN CAST('20181108' AS DATE) AND CAST('20181109' AS DATE)
GO 

