/*SELECT ID, 
ID_PESSOA, 
ACESSO, 
TIPO_ACESSO FROM ACESSO 
WHERE ID_PESSOA = 13 
AND ACESSO >= '16/08/2018 00:00:00' 
ORDER BY ID DESC*/

/*UPDATE ACESSO SET TIPO_ACESSO = 'E' WHERE ID = 9; */


/*DELETE FROM ACESSO WHERE ID = 9;*/

SELECT * FROM ACESSO