SELECT	DISTINCT
		'STATUS_AFV'=
		CASE  
		   WHEN PV.DATAEXCLUSAO IS NULL THEN 'ATIVO'
		   ELSE 'CANCELADO'
		END, 
		'STATUS_PROTHEUS' =
		CASE PV.CODIGOUNIDFAT 
			WHEN '02' THEN IIF((SELECT D_E_L_E_T_ FROM Protheus_Producao.dbo.SC5020 WHERE C5_NUM = TPV.NUMPEDIDOSOBEL AND D_E_L_E_T_ = '*') = '*', 'CANCELADO', '')
			WHEN '01' THEN IIF((SELECT D_E_L_E_T_ FROM Protheus_Producao.dbo.SC5010 WHERE C5_NUM = TPV.NUMPEDIDOSOBEL AND D_E_L_E_T_ = '*') = '*', 'CANCELADO', '')
			WHEN '04' THEN IIF((SELECT D_E_L_E_T_ FROM Protheus_Producao.dbo.SC5040 WHERE C5_NUM = TPV.NUMPEDIDOSOBEL AND D_E_L_E_T_ = '*') = '*', 'CANCELADO', '')
	    END, 
		'STATUS_PED' =		 
		 CASE(
			  CASE PV.CODIGOUNIDFAT 
				WHEN '02' THEN (SELECT C5_STAPED FROM Protheus_Producao.dbo.SC5020 WHERE C5_NUM = TPV.NUMPEDIDOSOBEL AND D_E_L_E_T_ = '') 
				WHEN '01' THEN (SELECT C5_STAPED FROM Protheus_Producao.dbo.SC5010 WHERE C5_NUM = TPV.NUMPEDIDOSOBEL AND D_E_L_E_T_ = '') 
				WHEN '04' THEN (SELECT C5_STAPED FROM Protheus_Producao.dbo.SC5040 WHERE C5_NUM = TPV.NUMPEDIDOSOBEL AND D_E_L_E_T_ = '') 
			  END
			 )
		  WHEN 'S' THEN 'COMERCIAL' 
          WHEN 'M' THEN 'MARGEM'
          WHEN 'C' THEN 'CREDITO'
          WHEN 'R' THEN 'REJEITADO'
          WHEN 'A' THEN 'AGENDAR'
          WHEN 'L' THEN 'ADM.PED.VENDA'
          WHEN 'D' THEN 'LIBERADO'
          WHEN 'T' THEN 'ROMANEIO' 
          WHEN 'O' THEN 'OUTROS PEDIDOS'
          WHEN 'P' THEN 'PED. PALLET'
          WHEN 'F' THEN 'FATURADO'
		END, 	 
        PV.NUMPEDIDO,
        PV.NUMPEDIDOAFV,
		'EMP' = 
		CASE PV.CODIGOUNIDFAT
			WHEN '02' THEN 'JMT'
			WHEN '04' THEN '3F'
			WHEN '01' THEN 'SOBEL'
        END,
		TPV.NUMPEDIDOSOBEL,
		PV.FLAGBLOQUEIOAFV AS BLOQ_WORKFLOW,
		LEFT(PV.CODIGOVENDEDORESP, 6) AS CODIGOVENDEDORRESP,
		TV.NOME AS NOMEVEND,			
		'SUPERVISOR' =
		CASE PV.CODIGOUNIDFAT 
			WHEN '02' THEN (SELECT A3_NOME FROM Protheus_Producao.dbo.SA3020 WHERE A3_COD = (SELECT A3_SUPER 
							FROM Protheus_Producao.dbo.SA3020							
							WHERE A3_COD COLLATE Latin1_General_CI_AS = LEFT(PV.CODIGOVENDEDORESP, 6)							 
							AND D_E_L_E_T_ = ''
							) AND D_E_L_E_T_ = '')
			WHEN '04' THEN (SELECT A3_NOME FROM Protheus_Producao.dbo.SA3040 WHERE A3_COD = (SELECT A3_SUPER 
							FROM Protheus_Producao.dbo.SA3040 
							WHERE A3_COD COLLATE Latin1_General_CI_AS = LEFT(PV.CODIGOVENDEDORESP, 6) 
							AND D_E_L_E_T_ = ''
							) AND D_E_L_E_T_ = '')
			WHEN '01' THEN (SELECT A3_NOME FROM Protheus_Producao.dbo.SA3010 WHERE A3_COD = (SELECT A3_SUPER 
							FROM Protheus_Producao.dbo.SA3010 
							WHERE A3_COD COLLATE Latin1_General_CI_AS = LEFT(PV.CODIGOVENDEDORESP, 6) 
							AND D_E_L_E_T_ = ''
							))
		END,
		PV.DATAPEDIDO,
		PV.HORAINICIAL,
		PV.HORAFINAL,
		LEFT(PV.CODIGOCLIENTE, 6) AS CODIGOCLIENTE,
		'RZSOCIAL' = (SELECT RAZAOSOCIAL FROM AFVServer_SOBEL_PRD.dbo.TE_CLIENTE WHERE CODIGO = PV.CODIGOCLIENTE),		
		CASE
		  WHEN PV.CODIGOTIPOPEDIDO = 'N' THEN 'NORMAL'
		  WHEN PV.CODIGOTIPOPEDIDO = 'F' THEN 'BONIFICAÇÃO'
		END AS TIPOPEDIDO,
		LEFT(PV.CODIGOTABPRECO, 3) AS CODIGOTABPRECO,
		PV.DATAIMPORTACAO,
		--'R$ ' + CAST(REPLACE(CONVERT(VARCHAR,CAST(ROUND( COALESCE(PV.VALORLIQUIDO, 0.0000) , 2) AS MONEY), 1), ',','.') AS VARCHAR(30)) AS VALORLIQUIDO, 
		--'R$ ' + CAST(REPLACE(CONVERT(VARCHAR,CAST(ROUND( COALESCE(PV.VALORBRUTO, 0.0000) , 2) AS MONEY), 1), ',','.') AS VARCHAR(30)) AS VALORBRUTO, 
	    PV.VALORLIQUIDO AS VALORLIQUIDO, 
		PV.VALORBRUTO AS VALORBRUTO, 
		ISNULL(TPV.QTDEITENS, (SELECT Q.QTDEITENS FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO Q WHERE PV.NUMPEDIDOAFV = Q.NUMPEDIDOAFV )) AS MIX, 
		ISNULL(TPV.VOLUME, (SELECT SUM(Q.QTDEVENDA) FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDOITEM Q WHERE PV.NUMPEDIDOAFV = Q.NUMPEDIDOAFV )) AS VOLUME,
		PV.CESP_NUMPEDIDOASSOC,
		'NUMPVASSOCPROTHEUS' = 
		 CASE PV.CODIGOUNIDFAT
			WHEN '02' THEN (SELECT C5_NUM FROM Protheus_Producao.dbo.SC5020 WHERE C5_HASHPT COLLATE Latin1_General_CI_AS = PV.CESP_NUMPEDIDOASSOC AND D_E_L_E_T_ = '' )
			WHEN '01' THEN (SELECT C5_NUM FROM Protheus_Producao.dbo.SC5010 WHERE C5_HASHPT COLLATE Latin1_General_CI_AS = PV.CESP_NUMPEDIDOASSOC AND D_E_L_E_T_ = '' )
			WHEN '04' THEN (SELECT C5_NUM FROM Protheus_Producao.dbo.SC5040 WHERE C5_HASHPT COLLATE Latin1_General_CI_AS = PV.CESP_NUMPEDIDOASSOC AND D_E_L_E_T_ = '' )
		 END,
		PV.OBSERVACAOAPROVADOR,
		PV.DESCRMOTIVOLIBERACAO
FROM AFVServer_SOBEL_PRD.dbo.T_PEDIDO PV
LEFT JOIN Protheus_Producao.dbo.T_PEDIDO_SOBEL TPV ON TPV.NUMPEDIDO = PV.NUMPEDIDO
LEFT JOIN AFVServer_SOBEL_PRD.dbo.T_VENDEDOR TV ON TV.CODIGOVENDEDORESP = PV.CODIGOVENDEDORESP
ORDER BY PV.NUMPEDIDO
GO
