/*
SET DATEFORMAT ymd; 
SELECT ACESSO.ACESSO AS H_ACESSO, 
PESSOA.ID as T_CODIGO,
ACESSO.TIPO_ACESSO as T_ACESSO, 
PESSOA.NOME as T_NOME,
CONVERT(VARCHAR(5),ACESSO.ACESSO,108) AS HORA_ACESSO 
from acesso 
INNER JOIN PESSOA on PESSOA.ID = ACESSO.ID_PESSOA WHERE PESSOA.ID 
IN (SELECT ID_PESSOA FROM PESSOA) AND ACESSO.ACESSO BETWEEN '2018-09-10' AND '2018-09-11' 
GROUP BY  
          PESSOA.ID,
		  PESSOA.NOME,
          ACESSO.ACESSO,
		  ACESSO.TIPO_ACESSO		           
ORDER BY T_NOME ASC
*/

--UPDATE PESSOA SET NOME = UPPER(NOME) WHERE ID = 34


--SELECT * FROM PESSOA
















/*select Count(P8_HOR) as Hora,
       P8_MAT,
	   P8_DATA
from SP8
group by 
         P8_MAT,
	     P8_DATA
having Count(P8_HOR)%2 = 1 


--SELECT * FROM SP8 WHERE P8_MAT = 133
*/

/*
UPDATE SP8
    SET SP8.D_E_L_E_T_='*'
FROM
  SP8 SP8_U
  INNER JOIN
  (
      SELECT SP8.P8_FILIAL,
             SP8.P8_MAT,
             SP8.P8_PAPONTA,
             SP8.P8_ORDEM
      FROM SP8
    WHERE SP8.D_E_L_E_T_=' '
    GROUP BY SP8.P8_FILIAL
            ,SP8.P8_MAT
            ,SP8.P8_PAPONTA
            ,SP8.P8_ORDEM
    HAVING ((COUNT(*)%2)=1)
   ) SP8_R
   ON  SP8_U.P8_FILIAL=SP8_R.P8_FILIAL
  AND SP8_U.P8_MAT=SP8_R.P8_MAT
  AND SP8_U.P8_PAPONTA=SP8_R.P8_PAPONTA
  AND SP8_U.P8_ORDEM=SP8_R.P8_ORDEM
WHERE SP8_U.D_E_L_E_T_=' ' 
*/
