USE Protheus_Producao
GO
SELECT  B2_LOCAL,
        B2_COD,
       ((B2_QATU - B2_RESERVA - B2_QEMP - B2_QACLASS - B2_QEMPSA - B2_QEMPPRJ - B2_QTNP) + B2_QNPT) - B2_QEMPPRE AS 'QDISP'
FROM SB2010 
--WHERE B2_COD LIKE '3%'
WHERE B2_COD = '1501.23.06X03L'
AND D_E_L_E_T_ = ''
GO

SELECT *
FROM SB2010
WHERE B2_COD LIKE '3%'
GO

/* Teste */
SELECT  B2_COD,
		B2_LOCAL,
		B2_QATU,
		B2_QPEDVEN
FROM SB2010
WHERE B2_QPEDVEN <> ''
AND D_E_L_E_T_ = ''
GO

EXEC sp_columns 'SB2010'
GO



