--SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = ACESSO

BEGIN TRANSACTION

DECLARE @DATABASE VARCHAR(100)
DECLARE @COLUNAS VARCHAR(8000)
DECLARE @TABELA_ORIGEM VARCHAR(100)
DECLARE @TABELA_DESTINO VARCHAR(100)

SET @DATABASE = 'tst_controle_acesso'
SET @TABELA_ORIGEM = 'ACESSO'
SET @TABELA_DESTINO = 'ACESSO_BKP'
SET @COLUNAS = 'ID_PESSOA, ACESSO, TIPO_ACESSO'

EXEC('SET IDENTITY_INSERT ' + @DATABASE + '.dbo.' + @TABELA_DESTINO + ' ON')
EXEC('INSERT INTO ' + @DATABASE + '.dbo.' + @TABELA_DESTINO +'(' + @COLUNAS+ ') SELECT '+ @COLUNAS +' FROM ' + @DATABASE + '.dbo.' + @TABELA_DESTINO );
EXEC('SET IDENTITY_INSERT ' + @DATABASE + '.dbo.' + @TABELA_DESTINO + '  OFF')
--ROLLBACK



