USE Protheus_Producao
GO
DECLARE @DTINI AS DATE, @DTFIN AS DATE
SET @DTINI = '20190101'
SET @DTFIN = '20190109'

SELECT EMP = 'SOBEL',
	   E1_PEDIDO AS PEDIDO, 
	   (SELECT C5_NOTA FROM SC5010 WHERE C5_NUM = SE1.E1_PEDIDO AND D_E_L_E_T_ = '') AS NOTAFISC, 
	   SE1.E1_NUM AS TITULO,
	   IIF(E1_SALDO = 0, 'BAIXADO', 'EM ABERTO') AS STATUS,
	   E1_EMISSAO AS DTEMISSAO
FROM SE1010 SE1 
WHERE E1_TIPO = 'NF'
AND E1_EMISSAO BETWEEN @DTINI AND @DTFIN

UNION ALL

SELECT EMP = 'JMT',
	   E1_PEDIDO AS PEDIDO, 
	   (SELECT C5_NOTA FROM SC5020 WHERE C5_NUM = SE1.E1_PEDIDO AND D_E_L_E_T_ = '') AS NOTAFISC, 
	   SE1.E1_NUM AS TITULO,
	   IIF(E1_SALDO = 0, 'BAIXADO', 'EM ABERTO') AS STATUS,
	   E1_EMISSAO AS DTEMISSAO
FROM SE1020 SE1 
WHERE E1_TIPO = 'NF'
AND E1_EMISSAO BETWEEN @DTINI AND @DTFIN

UNION ALL

SELECT EMP = '3F',
	   E1_PEDIDO AS PEDIDO, 
	   (SELECT C5_NOTA FROM SC5040 WHERE C5_NUM = SE1.E1_PEDIDO AND D_E_L_E_T_ = '') AS NOTAFISC, 
	   SE1.E1_NUM AS TITULO,
	   IIF(E1_SALDO = 0, 'BAIXADO', 'EM ABERTO') AS STATUS,
	   E1_EMISSAO AS DTEMISSAO
FROM SE1040 SE1 
WHERE E1_TIPO = 'NF'
AND E1_EMISSAO BETWEEN @DTINI AND @DTFIN
GO