/* AJUSTA O CUSTO EM SD1 */
DECLARE 
	@QUERY      NVARCHAR(MAX),
	@N_REG      INT,
	@CONT       INT,
	@CUSTO_ENT  FLOAT,
	@NEW_CUSTO  FLOAT,
	@QUANT      INT

BEGIN
	/* GET - NUMERO DE REGISTROS NA TABELA SD1 */
	SET @N_REG = (SELECT COUNT(R_E_C_N_O_) FROM SD1040)
	SET @CONT  = 1
	SET @QUERY = ''
	
	WHILE @CONT <= @N_REG
	BEGIN
		SET @CUSTO_ENT = (SELECT B1_UPRC 
						  FROM SB1040
						  WHERE B1_COD = (SELECT D1_COD FROM SD1040 WHERE R_E_C_N_O_ = @CONT ) 								
						  )
						  	   
		SET @QUANT	   = (SELECT D1_QUANT FROM SD1040 WHERE R_E_C_N_O_ = @CONT)
		SET @NEW_CUSTO = @CUSTO_ENT * @QUANT 
		
		SET @QUERY += ' UPDATE Protheus_Teste12.dbo.SD1040 SET D1_CUSTO  = ' + CAST(@NEW_CUSTO AS VARCHAR) + ','
		SET @QUERY += ' D1_CUSTO2 = ' + CAST((@NEW_CUSTO / 3.66) AS VARCHAR) + ' WHERE R_E_C_N_O_ = ' + CAST(@CONT AS VARCHAR) 
		PRINT @QUERY + 'char(10)'
		SET @CONT += 1
	END
END
