
CREATE FUNCTION [dbo].[F_SPLIT](@STRING VARCHAR(MAX), @DELIMITADOR VARCHAR(MAX)
) RETURNS @RESULT TABLE (ITENS VARCHAR(8000))
BEGIN
DECLARE @PARTE VARCHAR(8000)
WHILE CHARINDEX(@DELIMITADOR,@STRING,0) <> 0
BEGIN
SELECT
@PARTE=RTRIM(LTRIM(SUBSTRING(@STRING,1,CHARINDEX(@DELIMITADOR,@STRING,0)-1))),
@STRING=RTRIM(LTRIM(SUBSTRING(@STRING,CHARINDEX(@DELIMITADOR,@STRING,0)+LEN(@DELIMITADOR),LEN(@STRING))))
IF LEN(@PARTE) > 0
INSERT INTO @RESULT SELECT @PARTE
END

IF LEN(@STRING) > 0
INSERT INTO @RESULT SELECT @STRING
RETURN
END
GO


