USE controle_acesso
SET DATEFORMAT ymd; 
GO
SELECT A.ID_PESSOA,
	   A.ACESSO,
	   P.NOME, 
       CONVERT(VARCHAR(5),A.ACESSO,108) AS HORA_ACESSO, 
	   "TIPO" = 
	   CASE A.TIPO_ACESSO
		WHEN 'E' THEN 'Entrada'
		WHEN 'S' THEN 'Saída'
       END
FROM ACESSO A
INNER JOIN PESSOA P on P.ID = A.ID_PESSOA
WHERE ID_PESSOA  IN (SELECT ID FROM PESSOA WHERE STATUS = 'A') 
AND A.ACESSO BETWEEN CAST('2018-11-01' AS DATE) AND DATEADD(DAY, 1, CAST('2018-11-29' AS DATE))
ORDER BY P.NOME
GO
