USE controle_acesso_teste
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACESSO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PESSOA] [int] NULL,
	[ACESSO] [datetime] NULL,
	[TIPO_ACESSO] [char](1) NULL,
 CONSTRAINT [PK_ACESSO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PESSOA](
	[NOME] [varchar](250) NULL,
	[CEP] [varchar](8) NULL,
	[ENDERECO] [varchar](250) NULL,
	[NUMERO] [varchar](10) NULL,
	[CIDADE] [varchar](250) NULL,
	[BAIRRO] [varchar](250) NULL,
	[COMPLEMENTO] [varchar](50) NULL,
	[UF] [varchar](2) NULL,
	[TEL] [varchar](11) NULL,
	[CEL] [varchar](11) NULL,
	[RG] [varchar](9) NULL,
	[DATA_CADASTRO] [datetime] NULL,
	[STATUS] [char](1) NULL,
	[TEMPLATE] [varchar](8000) NULL,
	[CPF] [varchar](11) NULL,
	[CNPJ] [varchar](14) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SDP] [char](1) NULL,
	[SETOR] [varchar](50) NULL,
 CONSTRAINT [PK_PESSOA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
