USE controle_acesso
SET DATEFORMAT ymd; 
SELECT A.ID_PESSOA,
	   A.ACESSO,
	   P.NOME, 
       CONVERT(VARCHAR(5),A.ACESSO,108) AS HORA_ACESSO 
FROM ACESSO A
INNER JOIN PESSOA P on P.ID = A.ID_PESSOA
WHERE ID_PESSOA = 34 AND A.ACESSO 
BETWEEN CAST('2018-10-01' AS DATE) AND DATEADD(DAY, 1, CAST('2018-10-31' AS DATE))
ORDER BY ACESSO

