USE tst_controle_acesso
SET STATISTICS IO, TIME ON ---SET STATÍSTICO DA QUEY
SET DATEFORMAT ymd; --SET DE FORMATAÇÃO DE DATA
SELECT A.ID_PESSOA,
       P.ID,
	   A.ACESSO,
	   P.NOME, 
       CONVERT(VARCHAR(5),A.ACESSO,108) AS HORA_ACESSO 
FROM ACESSO A
INNER JOIN PESSOA P on P.ID = A.ID_PESSOA
WHERE ID_PESSOA = 34 AND A.ACESSO 
BETWEEN CAST('2018-10-01' AS DATE) AND CAST('2018-10-02' AS DATE)
ORDER BY HORA_ACESSO