SELECT J.C5_NUM AS J_C5NUM,
	   J.C5_EMISSAO AS J_EMISSAO, 
       J.C5_STAPED AS J_STAPED,
	   J.C5_ROMANEI AS J_ROMANEI,
	   J.C5_NOTA AS J_NOTA,
	   J.C5_CLIENTE AS J_CLIENTE,
	   J.C5_VEND1 AS J_VEND,
	   J.C5_CONTRA AS J_CONTRA,	 
	   F.C5_NUM AS F_C5NUM,
	   F.C5_EMISSAO AS F_EMISSAO, 
       F.C5_STAPED AS F_STAPED,
	   F.C5_ROMANEI AS F_ROMANEI,
	   F.C5_NOTA AS F_NOTA,
	   F.C5_CLIENTE AS F_CLIENTE,
	   F.C5_VEND1 AS F_VEND,
	   F.C5_CONTRA AS F_CONTRA	  
FROM SC5020 J 
LEFT JOIN SC5040 F ON F.C5_NUM = J.C5_NUM
WHERE J.C5_NOTA = '333333'
AND J.D_E_L_E_T_ = ''
AND F.D_E_L_E_T_ = '' 
AND F.C5_STAPED <> 'F'
GO



