USE Protheus_Producao
GO

SELECT C6_NUM AS PEDIDO,
       C5_ROMANEI AS ROMANEIO,
       SUM(C6_QTDVEN) AS "TOTAL_ROMANEIO"
FROM SC6040 SC6
INNER JOIN SC5040 SC5 ON C5_NUM = C6_NUM
WHERE C6_NUM IN (SELECT C5_NUM FROM SC5040 WHERE C5_ROMANEI IN (SELECT DISTINCT C5_ROMANEI FROM SC5040 WHERE C5_ROMANEI <> ''))
AND C5_ROMANEI <> ''
AND C5_NOTA <> ''
AND SC5.D_E_L_E_T_ = ''
AND SC6.D_E_L_E_T_ = ''
GROUP BY C6_NUM, C5_ROMANEI
ORDER BY C6_NUM ASC
GO


SELECT D2_DOC AS NOTA_FISCAL,
       D2_PEDIDO AS PEDIDO,
	   C5_ROMANEI AS ROMANEIO,
       SUM(D2_QUANT) AS "TOTAL_NOTA" 
FROM SD2040 SD2 
INNER JOIN SC5040 SC5 ON D2_PEDIDO = C5_NUM
WHERE D2_PEDIDO IN (SELECT C5_NUM FROM SC5040 WHERE C5_ROMANEI IN (SELECT DISTINCT C5_ROMANEI FROM SC5040 WHERE C5_ROMANEI <> ''))
AND C5_ROMANEI <> ''
AND C5_NOTA <> ''
AND SD2.D_E_L_E_T_ = ''
AND SC5.D_E_L_E_T_ = ''
GROUP BY D2_DOC, C5_ROMANEI, D2_PEDIDO
ORDER BY D2_PEDIDO 
GO

--------------------------------------------------------------------------------------------------------------------------------------------

SELECT C6_NUM AS PEDIDO,
       C5_ROMANEI AS ROMANEIO,
       SUM(C6_QTDVEN) AS "TOTAL_ROMANEIO",
	   SUM(D2_QUANT) AS "TOTAL_NF"
FROM SC6040 SC6
INNER JOIN SC5040 SC5 ON C5_NUM = C6_NUM
INNER JOIN SD2040 SD2 ON D2_PEDIDO = C5_NUM
WHERE C6_NUM IN (SELECT C5_NUM FROM SC5040 WHERE C5_ROMANEI IN (SELECT DISTINCT C5_ROMANEI FROM SC5040 WHERE C5_ROMANEI <> ''))
AND C5_ROMANEI <> ''
AND C5_NOTA <> ''
AND SC5.D_E_L_E_T_ = ''
AND SC6.D_E_L_E_T_ = ''
AND SD2.D_E_L_E_T_ = ''
GROUP BY C6_NUM, C5_ROMANEI
ORDER BY C6_NUM ASC
GO

















SELECT DISTINCT C5_ROMANEI FROM SC5040 WHERE C5_ROMANEI <> '' AND C5_NOTA <> '' AND D_E_L_E_T_ = ''
GO 





